### ISSUE TITLE
Broken textures from exporting Hotel Dusk

### ISSUE THREAD

**Issue by adrot** [scurest/MelonRipper#1]
Game: Hotel Dusk: Room 215 (E)
MelonRipper addon used (Blender): Latest
MelonDS used: Compiled around 05 April 2021
Blender version: 2.92

Issue:
Rooms from the game, the more textures they seem to use, the more distorted or different they are, compared to the original.

Methodology of investigation to arrive at the conclusion:
-Using the Debug Menu cheat code on the European version of Hotel Dusk, and pressing the SELECT button after making a selection on screen, like pressing ''START'' on the menu screen while holding it, or even holding SELECT before the game logos show up on boot.
-Selecting a map from the menu and dumping it.
-Using then GLIntercept and coupling it with an emulator, like Desmume, to extract textures from the same room, and comparing them.
Below is a picture that show the dump before and after manually changing the textures to the ones from GLIntercept.
So far, I have yet to see the same issue on the sequel of the series, Last Window: The Secret of Cape West.
![RENDER](https://user-images.githubusercontent.com/2317073/116007258-8cb40a00-a617-11eb-9973-3c1ac8907787.jpg)

**Comment by scurest** [comment]
Upload the .dump for me.

**Comment by adrot** [comment]
I dug up all solutions, it was actually the Blender add-on, it wasn't updated to the version of these last days, apologies for wasting your time, this was the cause of the bad texture output. here's the dump as requested, even though now it seems it's solved.
[melonrip-2021-04-27-21-55-39.zip](https://github.com/scurest/MelonRipper/files/6387874/melonrip-2021-04-27-21-55-39.zip)

**Comment by scurest** [comment]
Ah, yea, this was dfcdbd3. Incidentally, first time I've seen something that wasn't Yup. Looks like Xup I guess?
