### ISSUE TITLE
Wow, this is great! Amazing job! Do you think you can do a .sseq ripper?

### ISSUE THREAD

**Issue by LandonBoi123** [scurest/MelonRipper#12]
This is amazing! Do you think you could do another modification of MelonDS to make it rip sound data? all I need is to rip the .sseq of a currently playing song in the emulated game, if that's not possible, can you do .mid or .sdat?

**Comment by scurest** [comment]
Thanks. I don't plan to do anything for sound. Not very knowledgeable about audio.
