### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LandonAndEmma** [scurest/MelonRipper#14]
I use this program a lot but maybe you should add a setting where you can make the rips always point in the right direction instead of them pointing where the camera is, which is kind of stupid when you have to join multiple rips together. Also you should maybe want to update the code to the newest MelonDS version or don't but I would update it to 1.0 when it releases.

**Comment by scurest** [comment]
I don't know how to make the rips "always point in the right direction".

I've merged with upstream melonDS now. Also made a few tweaks to the .dump filenames. You can grab the updated version from the [release page](https://github.com/scurest/melonDS/releases/tag/MelonRipperBuild).
