### ISSUE TITLE
No texture output+Incorrect screen ripping

### ISSUE THREAD

**Issue by adrot** [scurest/MelonRipper#2]
**Games affected:** Hotel Dusk (E) and Last Window (E)
**MelonRipper addon used (Blender):** Latest (for real this time)
**MelonDS used:** Compiled around 05 April 2021 (was sent to me precompiled, had several issues doing it myself)
**Blender version:** 2.92

**Issues:**
1. (Hotel Dusk) Upon examining an area, and ripping it, the dump will display a plane of the left (TOP) screen, unless the bottom slider is moved, then it will display a 3D scene with no textures.
![image](https://user-images.githubusercontent.com/2317073/117558668-03c1b780-b088-11eb-96f2-84ddde9eaafc.png) ![image](https://user-images.githubusercontent.com/2317073/117557835-ff919c00-b07f-11eb-9605-12dc4b83c832.png) ![image](https://user-images.githubusercontent.com/2317073/117558640-c9581a80-b087-11eb-8058-440b755a28f6.png)

2. (Last Window) Upon entering a puzzle with 3D elements, and ripping it, the dump will display the left (TOP) screen with issues (doesn't help that in this game, sprites are split into puzzle pieces, GLIntercept is useless), instead of the 3D puzzle on the right (BOTTOM) screen.
![image](https://user-images.githubusercontent.com/2317073/117558703-3c619100-b088-11eb-99ff-d4f98df16c4b.png)
![image](https://user-images.githubusercontent.com/2317073/117558217-08846c80-b084-11eb-943b-aa145af30058.png)

**Probable cause:**
It is possible the ripper has priority by default on the top screen over the bottom, except if triggered by a save file or action/movement/animation on the bottom screen.

**Methods of recreation (without save files):**
1. Using the Debug Code of Hotel Dusk to select the Lobby map on the WALK THROUGH option or just starting the game and going over the unskippable intro, head to the couch in the Lobby, and select the blinking Magnifying Glass icon to examine it, then rip it. This will rip a plane of the top screen. Then move the slider, and rip again. You will have a 3D scene, textureless.
2. Start the game new. After the intro, talk to the guy in front of you. Whenever you have a Orange Question, ask the individual. When you eventually talk to Margaret Patrice, choose Inquire when offered to, and Ignore on the second occasion. after all of that is done, Examine the mailbox. Then tap the leftmost bottom mailbox and you'll enter a Puzzle. When you see the mailbox, don't press the combination dial, and rip the scene. The animation that follows after solving the Puzzle will make the ripper dump the 3d scene, but the scene is mirrored in the X axis, and upside down.

**Files (Savestates and dumps):**
1. [Hotel Dusk.zip](https://github.com/scurest/MelonRipper/files/6446842/Hotel.Dusk.zip)
[It is possible that the save files both will display the scene without a 2D plane, and just the 3D scene, unlike taking the saveless route, for some reason. Please use the one where no slider has been moved, first]
2. 
[Last Window.zip](https://github.com/scurest/MelonRipper/files/6446844/Last.Window.zip) [If you load the After puzzle scene, then load the Before puzzle scene, the ripper will focus on the 3D bottom screen and fix the issue]

**Comment by scurest** [comment]
So, the DS has two 2D engines to drive its two screens, but only one 3D engine. The 3D engine sends its output to only one of the 2D engines. If both screens are using 3D, the way that's done is it will capture a "screenshot" of the 3D scene, and the other 2D engine will use that 2D screenshot.

So (a) what the DS sends to the 3D engine isn't necessarily what's going to show up on screen, and (b) there's no way this could dump the "wrong screen"; it just dumps whatever is sent to the 3D engine on that frame.

-----

![](https://user-images.githubusercontent.com/2317073/117557835-ff919c00-b07f-11eb-9605-12dc4b83c832.png)

This is probably not shown on the screen, but used for object detection for the point-and-click. Each object has a unique color, so it probably renders this, saves a screenshot to memory, and when you click, it tests the color where you clicked to find out what object you clicked on.

-----

![](https://user-images.githubusercontent.com/2317073/117558640-c9581a80-b087-11eb-8058-440b755a28f6.png)

I don't know what's with this.

----

![](https://user-images.githubusercontent.com/2317073/117558217-08846c80-b084-11eb-943b-aa145af30058.png)

Is this `Malibox Before Puzzle.dump`? It doesn't look like that for me, it just looks like the top screen (using the `Front` view).

**Comment by adrot** [comment]
For the Mailbox Before Puzzle, I sent the wrong one, my bad again... This is what happens when I do this at 5AM with multiple uncatalogued dumps, it makes you paranoid...
[melonrip-2021-05-09-05-00-45.zip](https://github.com/scurest/MelonRipper/files/6448267/melonrip-2021-05-09-05-00-45.zip)
Can anything be fixed about the scenes, like, dumping the textures separately? There is a chance that this will sacrifice the accuracy like lighting etc, however, right? I mean, it is weird however that this issue doesn't happen in its sequel, Last Window, on the Mailbox area.
![image](https://user-images.githubusercontent.com/2317073/117584883-1edc0800-b118-11eb-98ba-a8d356624369.png)
![image](https://user-images.githubusercontent.com/2317073/117584953-81cd9f00-b118-11eb-9725-7327035e1668.png)
A dump for this scene too, just in case: 
[melonrip-2021-05-09-22-45-33.zip](https://github.com/scurest/MelonRipper/files/6448280/melonrip-2021-05-09-22-45-33.zip)

**Comment by scurest** [comment]
I dunno. This game seems like a pain so I'm not very interested in investigating it.

**Comment by adrot** [comment]
I can agree on the difficulty, it's been a years-long effort of mine.
Alright, thanks for your help.

**Comment by adrot** [comment]
Yo, I'm very glad to hear a new update on the matter after all this time. Now if only I could understand why I keep getting errors in compiling melonDS... not that savvy.

**Comment by scurest** [comment]
There's a link to a precompiled exe in the readme if you use windows.

**Comment by adrot** [comment]
Does that one also include your recent fix?

**Comment by scurest** [comment]
Should, it automatically updates when new commits are pushed.

**Comment by adrot** [comment]
Alright, thx a million.

**Comment by adrot** [comment]
Huge respect, it really works now! (Am not sure if the ground is like that in game cause the view angle is restricted and I don't have a freecam but it's a great step anyways)
![image](https://user-images.githubusercontent.com/2317073/139596965-5694f808-c935-4100-8dde-9bd9cbca98c8.png)

**Comment by scurest** [comment]
It does seem to be like that in the game. I hacked in an offset to the camera.

![Hotel Dusk](https://user-images.githubusercontent.com/11024420/139599088-e1409711-6f44-4a24-851d-8deaf4ec4150.png)

Actually the whole floor's topology is completely nuts lol.

**Comment by adrot** [comment]
Oh lol, I'd ask how you did that but it would probably be off-topic.

**Comment by scurest** [comment]
Just hacked it in; I stuck `PosMatrix[14] -= 12 << 12;` [here](https://github.com/scurest/melonDS/blob/50877c52ec3811437dc121ea3f4cf6fc4d49bb1a/src/GPU3D.cpp#L772) and recompiled. (I just kept trying different values til I found one that worked.)

**Comment by adrot** [comment]
Noted.
