### ISSUE TITLE
MelonRipper asign key option is missing

### ISSUE THREAD

**Issue by eros71-dev** [scurest/MelonRipper#3]
I've noticed that when compiling the last version as the date of this message (0.9.2), the assign option doesn't appear anymore in the Add-ons section.
![imagen](https://user-images.githubusercontent.com/16540103/117739931-a6e90d00-b1ff-11eb-8608-d266056b900e.png)

**Comment by scurest** [comment]
You need to compile the branch https://github.com/scurest/melonDS/tree/MelonRipper. It's branched off of melonDS 0.9.1, so if you have 0.9.2 you've compiling the wrong branch.
