### ISSUE TITLE
Keyboard mapping for ''[MelonRipper] Rip'' is missing

### ISSUE THREAD

**Issue by Hodorberg** [scurest/MelonRipper#4]
First off, I would like to state that I have zero experience with coding and this git stuff, and I stumbled upon your work when I was looking for a way to rip models from NDS games. Please excuse my inexperience. 

I managed to to follow your instruction at https://github.com/scurest/MelonRipper and got the MelonDS 0.9.1 up and running. But as the title stated, the keyboard mapping for ''[MelonRipper] Rip'' is missing. I also noticed that in the melonDS/src folder, the file MelonRipper.cpp and MelonRipper.h were also missing as well. I have no idea what went wrong, please help! Thank you so much for reading.

![nomelon](https://user-images.githubusercontent.com/84203808/118738035-434e8780-b870-11eb-8f68-d86ae03b8c0d.png)

**Comment by scurest** [comment]
On th ecommand line, go into your `melonDS` folder and run `git status` and `git remove -v`, and tell me what they say.

**Comment by Hodorberg** [comment]
![nomelon](https://user-images.githubusercontent.com/84203808/118747479-45badc80-b884-11eb-83b8-0c5aeea009bc.png)

Hope I did it properly!

**Comment by scurest** [comment]
Okay, so you're on the `master` branch. You need to be on the `MelonRipper` branch. Run

    git checkout MelonRipper

The MelonRipper.* files should now exist.

**Comment by Hodorberg** [comment]
Now I can see the files MelonRipper.cpp and MelonRipper.h in the ''src'' folder now, but there are still no key mapping option for the ''[MelonRipper] Rip'' when I run melonDS. I had run `git checkout MelonRipper` multiple times now, and restarted my computer as well.
![nomelon](https://user-images.githubusercontent.com/84203808/118751603-cc26ec80-b88b-11eb-931e-493ac3399489.png)

**Comment by scurest** [comment]
Did you rebuild after switching to the new branch?

**Comment by Hodorberg** [comment]
No, I have no idea how to rebuild. Where can I see the instructions to do so?

**Comment by scurest** [comment]
Go back into the `melonDS/build` folder and run `make` again.

**Comment by Hodorberg** [comment]
Okay, so I ran `make` and I still cannot see the key mapping option.
![nomelon](https://user-images.githubusercontent.com/84203808/118756264-c2ee4d80-b894-11eb-8ce7-9cf4980fcfa3.png)

**Comment by scurest** [comment]
I put up a continuous release with a precompiled EXE you can download instead of building melonDS yourself: https://github.com/scurest/melonDS/releases/tag/MelonRipperBuild. Try that instead.

**Comment by Hodorberg** [comment]
I finally got it running properly now thanks to your new upload. Thank you so so much for spending your time on helping me, and putting up with my questions! Stay safe and may you have a great year ahead of you!
