### ISSUE TITLE
Cannot Export Models

### ISSUE THREAD

**Issue by Musashi91** [scurest/MelonRipper#5]
I've started using MelonRipper to rip models from different NDS games, but after importing the .dump files to Blender, no matter what specific materials I try to remove, everything gets deleted, like the whole rip is connected to each other. Is there a way for me to export models, or remove materials, without deleting the whole import? Cause what I'm doing is for research, and reference for some personal projects.

**Comment by scurest** [comment]
Don't understand what you're doing, but it's just a regular Blender model, you can edit it just like any other. Just select the faces you don't want in edit mode and delete them.

You can always separate any mesh into multiple objects by material in edit mode by picking Mesh > Separate > By Material (shortcut: P).

**Comment by Musashi91** [comment]
Ok, that can work. Thanks.
