### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by helpwithxtract** [scurest/MelonRipper#7]
Hello! I am new to GitHub and I am not entirely sure how this site + it's etiquette works so my apologies if I am doing anything wrong.

When I use MelonRipper with an in-game model viewer (which some games have, for example Star Wars: Jedi Alliance), I am able to open the .dump file with Blender no problem. However, when I use MelonRipper during actual gameplay with any game, including the one I just mentioned, I get "Traceback (most recent call last)" followed by a large wall of text and no model shows up. This is an issue I sometimes have when opening certain models in Blender.

**Comment by scurest** [comment]
Thanks. The addon requires Blender 2.82 or later. You look like you have 2.81, so you'll have to install a later version.

The file works for me in 2.93 (3.0 came out a few days ago but I haven't upgraded yet).

(This is exactly the reason 2.82 is required btw; textures that use "mirror repeat" tiling are imported using a Pingpong node ([this trick](https://blender.stackexchange.com/questions/23475/how-to-get-mirrored-tiling-in-cycles/167035#167035)) which was only added in Blender 2.82.)
