### ISSUE TITLE
MelonDS crashes after starting a rom

### ISSUE THREAD

**Issue by Genard34** [scurest/MelonRipper#8]
when i start a rom the emulator crashes after a couple seconds

**Comment by scurest** [comment]
That's not much to go on. Does it happen with regular melonDS? If you run it from terminal, does it print anything when it crashes?

**Comment by Genard34** [comment]
> That's not much to go on. Does it happen with regular melonDS? If you run it from terminal, does it print anything when it crashes?

the normal build of melonds does not crash, its the ripper that crashes after starting a rom

**Comment by trit117** [comment]
Had the same issue. It works now that I built it myself.

**Comment by Genard34** [comment]
> Had the same issue. It works now that I built it myself.

nice, how do i build it?

**Comment by trit117** [comment]
follow the instructions on https://github.com/scurest/melonDS/tree/MelonRipper
make sure to use the melonripper branch
for me I had to download the repo and place it in the folder because using git clone https://github.com/Arisotura/melonDS is for the main branch and git clone https://github.com/scurest/melonDS/tree/MelonRipper couldnt be found.
if you have any other questions feel free to ask, or I can send you the one I built

**Comment by Genard34** [comment]
> follow the instructions on https://github.com/scurest/melonDS/tree/MelonRipper make sure to use the melonripper branch for me I had to download the repo and place it in the folder because using git clone https://github.com/Arisotura/melonDS is for the main branch and git clone https://github.com/scurest/melonDS/tree/MelonRipper couldnt be found. if you have any other questions feel free to ask, or I can send you the one I built

yes, can you sent me the one you built?

**Comment by trit117** [comment]
I don't know if there are any rules against it, but here you go. Happy ripping
[melonDS.zip](https://github.com/scurest/MelonRipper/files/8157455/melonDS.zip)
.

**Comment by scurest** [comment]
Can someone who can repro this test and see if it still happens with the latest binary?

**Comment by trit117** [comment]
> Can someone who can repro this test and see if it still happens with the latest binary?

Sure thing, ill test it when I get home :)

**Comment by trit117** [comment]
> Can someone who can repro this test and see if it still happens with the latest binary?

Alright, got to test it and it worked like a charm. Launched just fine, and ripped just fine.

**Comment by scurest** [comment]
Great! Thanks for testing!

**Comment by adrot** [comment]
I want to add some input to this issue that might add some light. The automated build of 0.9.3 worked for me fine in the past months until strangely this month, just crashing. The newer build didn't help either. But the clean build of MelonDS worked... I thought to rename the exe to just "MelonDS" and the rom miraculously booted up. Hope this may solve others who have similar issue.

**Comment by preland** [comment]
I believe that the same issue is occurring to me (MacOS). Attempting to run the modified version results in a crash after a few frames (Although I think that is just the emulator startup: it will flash white and then crash). This is with the most recent MelonRipper branch as of writing this, built from source.

A couple things I tried:
-Running it with/without using external BIOS files
-Running it with/without booting directly to the game (it will crash at the home menu, though it does have a noticable pause in loading when compared to direct boot)
-Running the app directly via command line
-Changing the name of both the application AND the executable (the application is the bundle, ie melonDS.app; the executable is within the application, ie melonDS.app/Contents/MacOS/melonDS) from "melonDS" to "MelonDS"

-Running unmodified melonDS, which works just fine

If you need me to paste logs I can do so, although the command-line logs look pretty bare. The only error I get is a segfault from the shell. It errors after printing ```WIFI: ON```.

P.S. This is unrelated to the issue, but is MelonRipper capable of dumping non-3D textures? It seems like there aren't really any tools that can do this anymore, so if MelonRipper can do that....

**Comment by scurest** [comment]
Run it under a debugger and tell me where it crashes.

> is MelonRipper capable of dumping non-3D textures?

No.
